require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
      - vendor/**/*
      - binstub/**/*
      - Gemfile*
      - Rakefile
  NewCops: enable

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/InitialIndentation:
  Exclude:
    - README.md

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/AbcSize:
  Max: 45

Metrics/BlockLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Naming/FileName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
